---
# tasks file for virl-packet-net-teardown

- name: include vaulted variable file
  include_vars:
    file: vault.yml

- name: get project id
  uri:
    url: https://api.packet.net/projects
    method: GET
    headers:
      accept: "application/json; version=1"
      content-type: "application/json"
      x-auth-token: "{{ api_token }}"
  register: project_info
  run_once: true

- name: set project_id fact
  set_fact:
    project_id: "{{ (project_info.json.projects | selectattr('name','equalto', project_name) | first).id }}"
  run_once: true

- name: print out project_id
  debug:
    msg: "The project_id is {{ project_id }}."

- name: "retrieve all device IDs for {{ project_name }}"
  uri:
    url: "https://api.packet.net/projects/{{ project_id }}/devices"
    method: GET
    headers:
      accept: "application/json; version=1"
      content-type: "application/json"
      x-auth-token: "{{ api_token }}"
  register: project_devices
  run_once: true


- name: teardown VIRL instance
  packet_device:
    auth_token: "{{ api_token }}"
    project_id: "{{ project_id }}"
    state: "{{ instance_state }}"
    device_ids: "{{ item.id }}"
  with_items: "{{ project_devices.json.devices }}"
